//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGTradesIn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cart()
        {
            this.CartGameCodes = new HashSet<CartGameCode>();
        }
    
        public int CartID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public int CreatedBy { get; set; }
        public byte[] isCheckedOut { get; set; }
        public string isCartCheckoutFinal { get; set; }
    
        public virtual UserGamer UserGamer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartGameCode> CartGameCodes { get; set; }
    }
}
