//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGTradesIn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GameCode()
        {
            this.CartGameCodes = new HashSet<CartGameCode>();
            this.Transcations = new HashSet<Transcation>();
            this.Transcations1 = new HashSet<Transcation>();
        }
    
        public int GameCodeID { get; set; }
        public string GameCodeImage { get; set; }
        public string GameCodeTitle { get; set; }
        public string GameCodeDescription { get; set; }
        public Nullable<double> GameCodePrice { get; set; }
        public Nullable<double> GameCodeDiscount { get; set; }
        public Nullable<System.DateTime> GameCodeAddedDate { get; set; }
        public int GameCodeAddedBy { get; set; }
        public string wantSwap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartGameCode> CartGameCodes { get; set; }
        public virtual UserGamer UserGamer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transcation> Transcations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transcation> Transcations1 { get; set; }
    }
}
