//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGTradesIn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public int ReplyID { get; set; }
        public string ReplyContent { get; set; }
        public int ForumID { get; set; }
        public int ReplyBy { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
    
        public virtual Forum Forum { get; set; }
        public virtual User User { get; set; }
    }
}
