//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGTradesIn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transcation
    {
        public int TransactionID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionResponse { get; set; }
        public int TransactionRequestedBy { get; set; }
        public int TransactionRequestedTo { get; set; }
        public int GameCodeOffer { get; set; }
        public int GameCodeRequested { get; set; }
    
        public virtual UserGamer UserGamer { get; set; }
        public virtual UserGamer UserGamer1 { get; set; }
        public virtual GameCode GameCode { get; set; }
        public virtual GameCode GameCode1 { get; set; }
    }
}
